package seckill.dao;

import seckill.dataobject.UserPasswordDA;

public interface UserPasswordDAMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    int insert(UserPasswordDA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    int insertSelective(UserPasswordDA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    UserPasswordDA selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 19 20:34:30 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDA record);
}